### ISSUE TITLE
I've been looking for alternative to Restream.io, however there a few issues.

### ISSUE THREAD

**Issue by lhorace** [jprjr/multistreamer#13]
1) What are the system requirements?

2) You are using PostgreSQL. Which is troublesome if you want to fit all this in 512MB container. :/
I have a separate MySQL instance.

?

**Comment by jprjr** [comment]
Regarding requirements: I think a good rule-of-thumb is to budget 1 CPU core per transcode. I currently run this (along with PostgreSQL, Redis, etc) on a 1CPU, 512MB VPS, and one of my outputs is transcoded. Right now, `ps` is reporting that nginx is using ~15MB of RAM, I've seen my instance get up to ~50MB while streaming.

You can run this and all the required services in a 512MB container, but I understand not wanting to setup Postgres if you're already running MySQL. I believe the Lapis framework supports MySQL, but I've also got some hand-written SQL, I'll have to check if everything's compatible.

**Comment by lhorace** [comment]
Alright thanks for the info. In the past, I find PostgreSQL to be heavy and sometimes it needs it's own instance (not like MySQL is any better).  I'll deploy it here on old box that I use as a hypervisor, it's has 4 cores. Typically, I'll probably trans code about 2 streams. I have another more powerful box but I'll need buy equipment for it. I might look into external VMs, I'll check into it.
