### ISSUE TITLE
[feature request] chat widget timeout and avatars

### ISSUE THREAD

**Issue by asquelt** [jprjr/multistreamer#18]
it would be really nice to have a chat widget url option to specify how long given chat message is visible, so that it's not obstructing space if nobody is chatting and there are only few old chat messages. alternatively there could be unix timestamp attached as message attribute, so that can be handled by some external javascript.

the second attribute that could be attached (and displayed if certain flag is switched) is user avatar if it was provided by upstream API.

**Comment by jprjr** [comment]
Both great ideas! I'll look into getting those done.

Implementing a chat message fadeout should be pretty easy. I'll also attach a message timestamp so people can implement their own fadeout functions.

The user icon also should be pretty straightforward, too.

**Comment by jprjr** [comment]
Just pushed version `10.2.0` (and the corresponding Docker version) which these features and more - check out the release notes here: https://github.com/jprjr/multistreamer/releases/tag/10.2.0

**Comment by jprjr** [comment]
Update: I managed to introduce a bug in Facebook reactions, version `10.2.1` corrects this

**Comment by jprjr** [comment]
This has been complete for a while, closing.
