### ISSUE TITLE
Cosmetic bug in the readme/instructions

### ISSUE THREAD

**Issue by lhorace** [jprjr/multistreamer#21]
Hi,

On the [install section for OpenResty](https://github.com/jprjr/multistreamer#install-openresty-with-rtmp):

```
...
cd ../luarocks-2.4.2
./configure \
  --prefix=/opt/openresty-rtmp \
  --with-lua=/opt/openresty-rtmp/luajit \
  --lua-suffix=jit \
  --with-lua-include=/opt/openresty-rtmp/luajit/include/luajit-2.1
```

No `make build`, `make install`, or `make bootstrap`? I am surprised I missed this on the first go around. :/

**Comment by jprjr** [comment]
That's embarrassing! Not sure how I managed to let that slip by for so long.

Just pushed updates to the README
