### ISSUE TITLE
More of a question than an issue

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#23]
So did I understand correctly that I need to create a Facebook App so I could have a key and a secret to use it with multistreamer? If I want to stream to an existing Facebook Page, would it be possible?

Im using Nvidia GeForce Experience to stream to my Facebook Page and Restream.io to stream to YouTube and Twitch. I just want to use one to make management easier. I came across your page but I am not sure if I would be able to do what I want with this.

**Comment by jprjr** [comment]
Yep! The Facebook app is to get a key/secret for connecting to Facebook, creating the new live video, pulling in comments, etc. It'll work with any existing pages, as well as your own profile, groups you admin, and events you admin
