### ISSUE TITLE
Twitch hook fails to auth against Kraken

### ISSUE THREAD

**Issue by k1ck3r** [jprjr/multistreamer#24]
helo, 

it seems that the Twitch made some changes to their API lately, because the connector fails once the user restarts the stream. Other connectors works just fine, starting stopping only breaks the twitch authentication. The following scenarios were tried:

1. New/old dev account - also resetting the secret ID doesn't work
2. Full and fresh install of multistream as well as different browser (tried: FireFox, IE10, Edge, Opera, Chrome, even in incognito mode)
3. Pushing the rtmp with only FB/YT enabled works, and once Twitch is turned on, it returns 'no client id specified'
4. Tried describing the auth return URL to either https/http - the result is the same
5. Checked everything db/nginx relations, configs etc.

Will kindly assist in any tests, or deployments. 

BR

**Comment by jprjr** [comment]
Question: does the stream have "require preview before going live" set to yes or no? That triggers a slightly different code path that could be affecting this.

Also when you say restart the stream, what amount of time is there between stopping and starting? seconds, minutes, hours?

**Comment by k1ck3r** [comment]
hey man! thanks for having a spare time exactly on holidays. unfortunately, tried both ways, twitch just need re-authenticate.

**Comment by jprjr** [comment]
That is really weird - I stream to Twitch about every week without issue (but I've never done multiple twitch streams within the same day). I'll try stopping/starting the same stream within a short time and see if that changes anything.

**Comment by k1ck3r** [comment]
i understand that i might not explaining correctly the issue, but everything beside twitch's authentication runs smooth, without any issues. in the matter of fact, if i setup a twitch stream (authenticate and approve) even if i start streaming from another IP, the rtmp flow works just fine. 

I'm not very into Twitch's API, but as far as i tried debugging it, i think it's related with some sort of data/hour OR a id which soon enough expires. The system itself acts like it never been authenticated - but again, have to wait few hours (my best try was 8 hour, then fails)

ps. if u don't mind meeting on discord, after 3-5 hours holiday here will be over, and i can share all my digging (eg. nginx logs, because first push differs from the last which fails, i think i saved some tcpdump for the sake of testing ;)

**Comment by jprjr** [comment]
Sure, I went ahead and setup a discord for Multistreamer-related talk - https://discord.gg/FfMAURN

**Comment by jprjr** [comment]
Going through issue - closing this since it's been fixed
