### ISSUE TITLE
Facebook stream suddenly stopped

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#27]
I had a stream configured to push to fb, yt and twitch.. after an hour or so the fb stream stopped but the two was still going. Any logs i can collect to help with this investigation?

**Comment by jprjr** [comment]
I've noticed I'll have random disconnects from time-to-time, my hunch would be this is also a random disconnect.

Right now, the code is structured so the second something goes wrong - it bails. I think the better long-term fix is to auto-restart ffmpeg on failures. I'll check on what options ffmpeg has for restarting on its own and add them into Multistreamer

**Comment by jprjr** [comment]
Hey hey - I just pushed out a new version of Multistreamer, version 11.1.0

It will attempt to automatically restart ffmpeg whenever there's a failure. By default, it's limited to 3 attempts within a single session, but you can change this with the "ffmpeg_max_attempts" config parameter.

**Comment by pogzie** [comment]
Feel free to close. If I experience the same issue, I think its possible to drop in another comment on this to reopen.

**Comment by pogzie** [comment]
Last test in issue #41 already presents a solid workflow (start via obs, wait for 30s for all services to initialize,  enjoy, stop via obs) is an acceptable workaround. The single delay might have been a fluke. Closing this issue now.
