### ISSUE TITLE
Preview Live stream

### ISSUE THREAD

**Issue by tvvignesh** [jprjr/multistreamer#29]
Hi. Amazing work with multistreamer. Tested it and its great! Just one thing.

The live stream preview does not load any video (even if play button is clicked) while the video streams properly to all services. I just get the same html5 video container like below.

![test](https://user-images.githubusercontent.com/1165845/35770485-e8335d52-0941-11e8-873c-5978834c2398.png)

PS: Will be using multistreamer from now on. Will give you feedback regularly. Good work.

**Comment by jprjr** [comment]
Hey hey, just giving you a notification to let you know I've seen this - I'm moving this week, so I'll likely get to take a look at it next week.

**Comment by k1ck3r** [comment]
personally, don't use the preview, and suggest you so. otherwise if you insist to have a video preview, will suggest you to look over for some players, not so biggy, but still ;)

**Comment by tomasguirao** [comment]
Waiting for preview... THX!!
