### ISSUE TITLE
Mixer Chatbox bug

### ISSUE THREAD

**Issue by tvvignesh** [jprjr/multistreamer#30]
When using mixer, some error is also popping up on my chatbox like below once I stopped my stream. I had 2 chat boxes open, and one of them showed it right and other had it with this error.

![test1](https://user-images.githubusercontent.com/1165845/35770522-cfbb57c4-0942-11e8-926d-8692b8f48164.png)

**Comment by jprjr** [comment]
Hey hey, just giving you a notification to let you know I've seen this - I'm moving this week, so I'll likely get to take a look at it next week.

Off the top of my head, I haven't taken a look at the mixer code in a while so there's a good chance something's out-of-date.

**Comment by jprjr** [comment]
Hey, I sat down today to troubleshoot this bug. Can you let me know what browser you're using? I haven't been able to replicate this on Google Chrome

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
