### ISSUE TITLE
Instructions for Deploying to ARM Based Machines

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#33]
Hi, I filed an issue in the Docker repo of Multistreamer but it seems that its a bit complicated to do an automated build to with ARM. So I'm writing this to ask if theres any specific instructions to install/build this in an ARM based machine such as a Raspberry Pi?

Im having trouble with keeping my Multistreamer deployment stable in my ESXi machine since I occasionally shut it down during weekends (I use it for work) and at times when booting the VM where Multistreamer is installed, everything goes to utter crap (ie. not working, not pushing streams, etc).

I'd rather have my extra RPi forever turned on for Multistreamer purposes than have a power hungry dedicated x86 machine for this. I've also observed that Multistreamer works pretty well resource wise so I think an RPi3 would have enough power to handle streaming for 1 or 2 accounts.

**Comment by jprjr** [comment]
Hey, sorry for taking so long on that. My RPi is still in a box to get unpacked.

There's a few things you'd have to change in the Dockerfile to use this on an RPi:

First, I think you need to change the `FROM` line to use an arm version of alpine. I'm not sure what most people use for their ARM docker images, so I can't give any real tips there.

You'll also need to find the lines that pull in s6-overlay and sockexec:

```
  curl -R -L -o s6-overlay-amd64.tar.gz \
    https://github.com/just-containers/s6-overlay/releases/download/v$S6_OVERLAY_VER/s6-overlay-amd64.tar.gz  && \
  curl -R -L -o sockexec-x86_64-linux-musl.tar.gz \
    https://github.com/jprjr/sockexec/releases/download/$SOCKEXEC_VER/sockexec-x86_64-linux-musl.tar.gz && \
  curl -R -L -o openresty-$OPENRESTY_VER.tar.gz \
    https://openresty.org/download/openresty-$OPENRESTY_VER.tar.gz && \
  curl -R -L -o nginx-rtmp-module-$NGINX_RTMP_VER.tar.gz \
    https://github.com/arut/nginx-rtmp-module/archive/v$NGINX_RTMP_VER.tar.gz && \
  curl -R -L -o luarocks-$LUAROCKS_VER.tar.gz \
    http://luarocks.github.io/luarocks/releases/luarocks-$LUAROCKS_VER.tar.gz && \
  tar xzf openresty-$OPENRESTY_VER.tar.gz && \
  tar xzf nginx-rtmp-module-$NGINX_RTMP_VER.tar.gz && \
  tar xzf luarocks-$LUAROCKS_VER.tar.gz && \
  tar xzf s6-overlay-amd64.tar.gz -C / && \
  tar xzf sockexec-x86_64-linux-musl.tar.gz -C /usr && \
  cd openresty-$OPENRESTY_VER && \
```
and change those to use ARM binaries.

The armhf s6-overlay is at https://github.com/just-containers/s6-overlay/releases/download/v1.21.2.2/s6-overlay-armhf.tar.gz

The armhf sockexec is at https://github.com/jprjr/sockexec/releases/download/2.0.3/sockexec-arm-linux-musleabihf.tar.gz

**Comment by pogzie** [comment]
Nice. Will add this to my todo this weekend. I tried last week and the sheer number of dependencies that I would need to find the ARM version for overwhelmed me. 

I just shutdown my Pi, chucked it in my drawer and got myself a beer. :D 

Will let you know if incase I get far with this and document for additional instructions.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
