### ISSUE TITLE
not pushing to some Custom RTMP like Mips.tv

### ISSUE THREAD

**Issue by jprjr** [jprjr/multistreamer#36]
_From @mourin00 on September 14, 2017 13:31_

i tested multistreamer and work fine with youtube, vk ,fb ... but not pushing to some Cutom RTMP like Mips.tv 

_Copied from original issue: jprjr/docker-multistreamer#5_

**Comment by jprjr** [comment]
I'm not familiar with mips - do they require authentication or anything like that? Do they have any tutorials on say, setting up OBS/Xsplit I can take a look at?

**Comment by jprjr** [comment]
_From @mourin00 on September 20, 2017 16:27_

they dont request authentication and wihtout any tutorials or setting they just give me FMS URL : rtmp://cdn.mipspublisher.com/live and Stream Name : .... and it work fine in OBS

**Comment by jprjr** [comment]
I've tried looking into this, I've yet to get mips.tv to work with anything - OBS, ffmpeg, Multistreamer.

If anybody can come up with a working ffmpeg commandline for pushing to MIPS I'll take another look but for now I'm just closing this issue.

cc @mourin00

**Comment by Fran008** [comment]
Helllo.

I am trying to publish into mips.tv from VLC with the next command:

#duplicate{dst=display,dst="transcode{vcodec=h264,width=512,height=288,acodec=aac,ab=128,vb=300,samplerate=22050}:std{access=rtmp,mux=ffmpeg{mux=flv},dst=rtmp://cdn.mipspublisher.com/live/channelname?key=39e2027e&id=272237}"}

Did you find any solution to the authentication chain? I have tried with ffmpeg too... and it does not work either.

ffmpeg -re -i http://ccma-tva-es-abertis-live.hls.adaptive.level3.net/es/ngrp:c33_web/chunklist_b548000.m3u8 -b:v 300k -c:v libx264 -sample_rate 44100 -acodec aac -f flv "rtmp://cdn.mipspublisher.com/live/gianfranco?key=39e2017e&id=272731"

It gives the next message:

[rtmp @ 0x80149850] Unknown connect error (unsupported authentication method?)
[rtmp @ 0x80149850] Server error: Connection failed: Application rejected connection.
rtmp://cdn.mipspublisher.com/live/gianfranco?key=39e2017e&id=272731ffmpeg: Unknown error occurred

Thank you very much!
