### ISSUE TITLE
Missing closing fieldset tag

### ISSUE THREAD

**Issue by Voletek** [jprjr/multistreamer#38]
in file "/opt/multistreamer/multistreamer/lib/multistreamer/views/stream-permissions.etlua"

after line 36 the form is missing a closing fieldset tag
```
<option value="1" <% if other_user.metadata_level == 1 then %>selected<% end %>>View Metadata</option>
<option value="2" <% if other_user.metadata_level == 2 then %>selected<% end %>>Edit Metadata</option>
</select>
</div>
</fieldset>   <-- this needs to be added

<% end %>
```

other wise if you are sharing multiple accounts the bowser will embed a fieldset inside a fieldset making the markup look crazy

**Comment by jprjr** [comment]
Fixed! Just pushed up version 11.0.7 with the fix
