### ISSUE TITLE
Chat stopped showing messages

### ISSUE THREAD

**Issue by Llorx** [jprjr/multistreamer#39]
Easy as that. Stopped showing Twitch messages but YT messages were shown. Kinda weird. This happened in the middle of a stream. F5 the chat window don't fixed this.

I'm using docker so don't know what to do to get logs and such.

**Comment by jprjr** [comment]
Yeah, I've had that happen a few times myself. I've stepped up the logging on my main instance so I can try catching it next time it happens. It seems like I just get disconnected from Twitch IRC

**Comment by jprjr** [comment]
Just pushed 11.3.3 with some changes that should hopefully keep Twitch chat running.

It uses SSL instead of plain-text IRC now, this should prevent the stream from being mucked with by firewalls etc. If it gets disconnected, it keeps trying to reconnect instead of attempting to reconnect once.

**Comment by jprjr** [comment]
Found the real error - Twitch IRC sends attributes along with messages, one of which is "display-name"

In the past, I've seen them send an empty "display-name" attribute before, so I'd check if it was empty. It looks like they'll also sometimes just not send the attribute at all, which was the bug - I assumed the attribute would always be there.

New update will try to use the display-name attribute, but fallback to the IRC nick if it's missing or empty.

**Comment by Llorx** [comment]
Was just going to update. Going to wait for this new update.

**Comment by jprjr** [comment]
Pushed up a new release - 11.4.2 with a fix. Building Docker images now

**Comment by Llorx** [comment]
Tested docker build `11.4.2-1` and happened again :-/ Stopped receiving Twitch chat messages.

Where can I get the logs to see what is happening?

**Comment by jprjr** [comment]
If you `docker exec` into your image, you can get to `/var/log/multistreamer` - all the logs are in there. There's a `current` file, along with other files that end in `.s`

I forget the exact syntax off the top of my head, but if you run `docker ps` to see a list of images, there should be one with `multistreamer` in the name - grab the name of that image, then:

```
docker exec -ti (image name) /bin/bash
ls -lh /var/log/multistreamer
```

You can just cat them, or install ssh and scp them to another box, etc.

I'll change the default `docker-compose` file to mount the logs as a volume - then you'd be able to just get to them from your box instead of running `docker-exec`

**Comment by jprjr** [comment]
Hey hey, I had this same error happen to me just now, when somebody hosted my stream - the IRC message came in like:

```
Apr 11 21:06:36 stream multistreamer[425]: 2018/04/11 21:06:36 [debug] 603#0: *5 [lua] client.lua:40: log_parse_line(): [IRC] :jtv!jtv@jtv.tmi.twitch.t
v PRIVMSG gamethattune :Equitem87 is now hosting you.
Apr 11 21:06:36 stream multistreamer[425]: 2018/04/11 21:06:36 [error] 603#0: *5 lua user thread aborted: runtime error: /opt/multistreamer/lib/multist
reamer/networks/twitch.lua:559: attempt to concatenate local 'userid' (a nil value)
```

So basically, I can't assume I have *any* of the tags on IRC messages. I'll get this fixed shortly!
