### ISSUE TITLE
Delays in YouTube

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#41]
Upon doing a stream just a couple of hours ago, I noticed something odd. I use OBS to push my stream to Multistreamer which then pushes to Facebook, YouTube and Twitch. Making sure that my stream session was good, I checked the videos for Facebook, which showed the complete video; Twitch also showed the complete video in the archives and upon checking YouTube, it ended abruptly, around 30 seconds before I actually ended the stream. 

My procedure of ending the stream is via OBS. What I did after ending the OBS stream, I noticed that Multistreamer still has the `Go Live!` button still grayed out and refreshed the page accordingly for me to check and make sure that `Go Live!` and `Stop Pushing` are both disabled. 

My hypothesis is that while OBS sent a signal to stop the stream, there might be some left over data that Multistreamer needs to send to YouTube, but since I hit the refresh button, it stopped abruptly. 

FB video length: 42:24 https://www.facebook.com/1549289731752927/videos/2067338696614692/
Twitch video length: 42:08 https://www.twitch.tv/videos/235516506
YouTube video length: 40:28 https://www.youtube.com/watch?v=yzLOhz6Mznk

What is the correct process to properly end a stream?

**Comment by jprjr** [comment]
That's something I've been trying to figure out for some time myself - you basically hit the nail on the head. There's still video data that needs to be uploaded. I think this is really a limitation of the RTMP module - I would have the exact same thing happen when I just used the rtmp module directly.

My workaround is to have some scenes in OBS for starting and stopping. So I'll start with a basically blank screen that says "Hey I'm starting soon" and end with a blank screen that says "thanks for watching". When I end my stream, I switch to that "thanks" scene and let it keep going for another minute before I actually stop the stream.

**Comment by pogzie** [comment]
Hey thanks for the clarification! I like YouTubes quality and speed so I just tend to use YT for archival footage. Ill probably just add buffer to the start and end to cover everything until we get to figure out if this is indeed a limitation of the RTMP module. 

Maybe some other users who has subs in restream would be able to check. I assume they're just using the same implem as you and just charges for custom RTMP. lol

**Comment by pogzie** [comment]
I was getting data on this but I ran into another ?bug? which I will file into another separate thread. 

I streamed today to FB, Twitch, and YouTube. I used MSI Afterburner with the system time enabled so I know when it would start. My settings for Multistreamer is to push live as soon as OBS starts. 

Pressed the start stream button in OBS 23:51:00 and relatively, it took a bit of time for the streams to be broadcasted, numbers are below: 

YT: 23:51:31 started
FB: 23:51:14 started
Twitch: 23:51:30 started

Not bad, I attributed this to Multistreamer coordinating with the necessary API endpoints good advice is to indeed do a filler from the start and end. 

Regarding the end of the stream, I dont have any data yet, (more info on why on my next issue filing).

**Comment by jprjr** [comment]
Oh yeah, YouTube always takes a bit to start. In the YouTube API, you have to start pushing video, then poll their endpoint to see if its in a "ready" type status. Once it is, you can trigger the actual "go live" on YouTube. In my testing, it always takes about 30 seconds or so until YouTube is ready.

**Comment by jprjr** [comment]
Hey, just a small update. Multistreamer now polls YouTube more often to see if it's ready to go live (from every 30 seconds to every 5 seconds). Hopefully this will reduce some of that delay.

**Comment by pogzie** [comment]
honestly I think this isnt much of a big deal (starting) since indeed it takes time for the application to actually connect.. an added green light on the dashboard on the status of the connection of the services would be good.. a want but not a need. thanks for working on this! 

if you want you could close this or keep this open until I get the timestamps for start/end in conjunction to when i pressed the obs button to start/end. at least you would have data to chew on to solve the stop problem (i think the stop is a bigger problem)

**Comment by pogzie** [comment]
Ok I was able to get the data. I think the recent fixes resolved the issue (or probably starting/ending the stream using OBS works better). 

OBS stream start: 18:50:00
OBS stream end: 19:15:30

Facebook: 18:50:15 - 19:15:30 (https://www.facebook.com/1549289731752927/videos/2086123858069509/)
YouTube: 18:50:23 - 19:15:30 (https://www.youtube.com/watch?v=V7qoJwgUXrg)
Twitch: 18:50:32 - 16:15:30 (https://www.twitch.tv/videos/240782945)

Thanks for the hard work on the updates. This ticket can be closed (again)
