### ISSUE TITLE
Facebook API Change?

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#43]
Im getting messages like this in my email: 

> Your app is receiving errors from GET {invalid-id-id}/comments
>  
> In the last three hours 100% of the calls to the method GET {invalid-id-id}/comments resulted in errors.
> 
> Error Code: 100
> Error Description: Invalid parameter
> Error Count: 3564
> 
> This may be result of a recent change you made to PogzNet Multistreamer, or a failure to comply with a recent breaking change.
> For more information about error codes and recovery tactics, please visit our documentation.
> If the error rate has not been resolved after 3 days, we'll send you another alert.
>  
> You can view this and other Developer Notifications related to your app, in the App Dashboard.

Something I need to be concerned about?

**Comment by jprjr** [comment]
Fixed in... man I've done too many tiny releases. It should be fixed in whatever the latest release is.
