### ISSUE TITLE
Request: stream key + username

### ISSUE THREAD

**Issue by k1ck3r** [jprjr/multistreamer#44]
Hello,

would like to kindly ask JprJR to add the username to the stream key, no matter with additional function or replace current one (ideally to have a tick box for attach the username to the stream key). Asking this only for easily monitor through the RTMP stats functions of the Nginx module, and because lately don't have a minute spare time, to additionally edit your code. Will greatly appreciate your effort.

thanks in advance

**Comment by jprjr** [comment]
I'll do you one better - I'll just add the username into the stats xml!

I just pushed up version 11.3.0 that scans the stats XML for UUIDs. When it finds them, it inserts the username and stream title, so you'll get output like:

```XML
<?xml version="1.0" encoding="utf-8" ?>
<rtmp>
<nginx_version>1.13.6</nginx_version>
<nginx_rtmp_version>1.1.4</nginx_rtmp_version>
<compiler>gcc 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.9) </compiler>
<built>Feb 28 2018 13:26:32</built>
<pid>27258</pid>
<uptime>6</uptime>
<naccepted>1</naccepted>
<bw_in>0</bw_in>
<bytes_in>607305</bytes_in>
<bw_out>0</bw_out>
<bytes_out>409</bytes_out>
<server>
<application>
<name>multistreamer</name>
<live>
<stream>
<name>e70dc878-981e-434e-aea0-c9bca97f9574</name>
<user>john</user>
<title>Let's make some stats</title>
<time>3526</time><bw_in>0</bw_in>
<bytes_in>604879</bytes_in>
<bw_out>0</bw_out>
<bytes_out>0</bytes_out>
<bw_audio>0</bw_audio>
<bw_video>0</bw_video>
<client><id>23</id><address>::ffff:192.168.59.1</address><time>3624</time><flashver>FMLE/3.0 (compatible; FMSc/1.0)</flashver><swfurl>rtmp://stream-dev.jrjrtech.com:1935/multistreamer</swfurl><dropped>0</dropped><avsync>7</avsync><timestamp>2306</timestamp><publishing/><active/></client>
<meta><video><width>1280</width><height>720</height><frame_rate>30</frame_rate><codec>H264</codec><profile>High</profile><compat>0</compat><level>3.1</level></video><audio><codec>AAC</codec><profile>LC</profile><channels>2</channels><sample_rate>48000</sample_rate></audio></meta>
<nclients>1</nclients>
<publishing/>
<active/>
</stream>
<nclients>1</nclients>
</live>
</application>
</server>
</rtmp>
```

This is available at "/stats", like "example.com/stats"

Changing the key format winds up being a good amount of effort, it requires a schema change to the database. This should let you monitor what you need without changing the database schema.

**Comment by k1ck3r** [comment]
that's incredible! thank you so much for your time!!!
