### ISSUE TITLE
Feature request for night mode UI

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#46]
Just wondering if its possible to have a dark/night mode for the Multistreamer UI? If theres any way you can point me to which files are edited along with a template file with test data, I think I can do so myself. 

I think majority of the people here are using this for streaming gaming, I tend to use my other PC to monitor/start the stream and the glare of the light UI is overpowering my other screen. (yes, I know I can just turn off the monitor, but surely there _is_ a better way.)

**Comment by k1ck3r** [comment]
i doubt that JPR will have something against editing the css used. feel free to add the feature :)

**Comment by jprjr** [comment]
That's a great idea!

I think the best way to go about it is to:

1. add a new field to the user table to store preferences. It can just be a blob of JSON
2. Add a drop-down to the "profile" section so a user can change between night mode and regular mode
3. Then `lib/multistreamer/views/chatlayout.etlua` can conditionally include a nightmode CSS file, which has overrides for the colors used

I should be able to get those steps done and get a stubbed night-mode CSS file going, which you could then edit

**Comment by pogzie** [comment]
Man, I was halfway through tampering the CSS via dev tools.. and was almost done with a dark version until I happen to clink a link which re-loaded the default css. *facepalm*

I was planning to just 'fetch' my night mode css code from an upload side and just sideload it via a command when I launch the container. 

Any implementation would be appreciated. I dont really need customizations like a banner photo or font change or what.. Just something dark. 

Thanks!

**Comment by jprjr** [comment]
One not-well-documented feature is you can have local overrides for CSS, Javascript, images, etc.

So, in the docker version, you can mount a volume in the container at `/home/multistreamer/share/html/local/css/multistreamer.css`, and it will serve that css file instead of the default.

So in your `docker-compose.override.yml` file, you could have a volume line like:

```
- /some/path/wherever/css:/home/multistreamer/share/html/local/css
```

Copy multistreamer.css from this repo to `/some/path/wherever/css` and edit as needed.

That would be really helpful, you could submit it later on for the proper "night mode override" file

**Comment by jprjr** [comment]
Alright, I just pushed 11.4.0 which has a basic night-mode UI. It can be set in the profile, or it can be set anytime by adding "night_mode=true" to any URL (for the chat widget, for example). Also, putting "night_mode=(whatever)" will always override what a user's set in their profile.

I'm going to consider "night mode" kind of a beta feature right now, I'm sure there's parts of the CSS that need to be updated.

**Comment by pogzie** [comment]
thankssss!

**Comment by pogzie** [comment]
Weird, I redeployed with the same config, everything was fine from last night but botched after I redeployed today. 

```
Error
[string "etlua"]:27: attempt to index global 'user' (a nil value)
Traceback
stack traceback:
	[string "etlua"]:27: in function 'run'
	.../multistreamer/lua_modules/share/lua/5.1/lapis/etlua.lua:158: in function 'render'
	...ultistreamer/lua_modules/share/lua/5.1/lapis/request.lua:242: in function 'render'
	...streamer/lua_modules/share/lua/5.1/lapis/application.lua:136: in function <...streamer/lua_modules/share/lua/5.1/lapis/application.lua:135>
	[C]: in function 'xpcall'
	...streamer/lua_modules/share/lua/5.1/lapis/application.lua:159: in function 'dispatch'
	.../multistreamer/lua_modules/share/lua/5.1/lapis/nginx.lua:215: in function 'serve'
	content_by_lua(nginx.conf:69):2: in function <content_by_lua(nginx.conf:69):1>
```

**Comment by k1ck3r** [comment]
i can confirm, with 11.4.0 the above error shows.

**Comment by jprjr** [comment]
Oh wow, that's bad on my part. I tested nearly everything except for logging out.

Since there's no "user" object if you're not logged in, I can't exactly check for the user's preferences, can I? Fix incoming

**Comment by jprjr** [comment]
Just pushed up tag 11.4.1, I've got the docker images building right now

**Comment by pogzie** [comment]
for some reason, i just pulled now, still the same. i will check the container logs

ps: im filing a ticket (low prio) if you can pipe the logs to stderr/stdout so i can easily retrieve them without docker exec (through DC/OS)

**Comment by jprjr** [comment]
Regarding logs: I can do that, but in the meantime I'd just make /var/log/multistreamer (or all of /var/log) a volume to some path on the host. That should also save you from having to docker exec, and keep logs around as you stop/destroy/restart containers

**Comment by pogzie** [comment]
Awwwwyis. Solid. 

![awyis](https://user-images.githubusercontent.com/1250064/37711425-a7bb3622-2d4b-11e8-8074-5dc6c5033019.PNG)

**Comment by pogzie** [comment]
Marking as resolved. Will file new issues if UI color theme is mis-matched at some sections.
