### ISSUE TITLE
Feature request to clone/copy stream details

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#47]
I've started to create multiple streams rather than editing the stream information manually everytime. I would just opt to create streams in Multistreamer and different profile in OBS and switch accordingly depending on the game im playing. 

If its possible, I would like to request the option to clone a stream (which accounts are active, all the information, etc.) since that would make everything easier by just cloning and doing minor edits than putting all values again over and over.

Another way to approach this is to use templates (like how Switchboard Live Cloud does it) so its easier to switch what type you're streaming with a single configuration for RTMP/keys.

**Comment by jprjr** [comment]
Just pushed up version 12.2.0, which has export/import buttons under the stream's "advanced" tab.

**Comment by pogzie** [comment]
Saw the feature but I think due to the fact that im importing/cloning one stream config, its rejecting it probably due to duplicate names. 

Im thinking, is there a way to "import from" an existing to automate the JSON export and then JSON import and just ignore the stream name value or something? 

Not that important though would improve quality of life.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
