### ISSUE TITLE
RTMP URL missing prefix

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#48]
I was supposed to stream today and gather more information about the start/stop problem but I've faced several problems. I will be individually filing an issue for those. 

Upon checking, I noticed that even if I have a prefix set, the suggested RTMP URL in the dashboard doesnt contain my prefix. Using it without the prefix doesnt work, I had to go back to my config and add /multistreamer on OBS for me to be able to connect.

**Comment by k1ck3r** [comment]
the rtmp URL is based on your configuration in /etc/multistreamer/config.yaml from the option:

rtmp_prefix: 'multistreamer'

don't forget to restart the service in order to apply the changes

**Comment by pogzie** [comment]
I clearly have ` "MULTISTREAMER_RTMP_PREFIX": "multistreamer"` set as an option. It was appearing correctly a couple of versions ago with the /multistreamer so I assume that the new codepush had this yanked accidentally. 

PS: its that format because its passed as an env variable since I launch multistreamer using dc/os. 

I docker exec'ed into my container and its indeed set. 

```
bash-4.4# cat /etc/multistreamer/config.yaml |grep rtmp_prefix
rtmp_prefix: 'multistreamer'
bash-4.4#
```

I've also attached a screenshot of that containers multistreamer running fine with the incorrect RTMP link on the UI. So yes, im sure that the update accidentally obliterated this. 

![rtmp](https://user-images.githubusercontent.com/1250064/37652764-9b19bf26-2c77-11e8-8323-87109e5e11a7.PNG)

**Comment by jprjr** [comment]
Yeah, that's definitely a bug on my part.

If somebody doesn't have `rtmp_prefix` or `MULTISTREAMER_RTMP_PREFIX` set (or if it's set to an empty string), multistreamer over-rides it anyway.

This happened when I replaced the plain-text paragraph with an input box (so users can lazily triple-click and select the entire box without breaking out). Getting it fixed now.
