### ISSUE TITLE
Error message when starting the stream

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#49]
After I was able to figure out the correct RTMP, I tried (settings currently in preview before streaming) to start my stream and got the following message: 

```
Failed to start pusher: {"error":"Bad Request","status":400,"message":"No client id specified"}
```

**Comment by k1ck3r** [comment]
try to re-authenticate against twitch/youtube again. this message appears when the id pushed from multistreamer to upper streaming service doesn't contain anything. also will solve the issue which you are having with OBS once there are defined and switched on authenticated upper streaming services.

**Comment by pogzie** [comment]
probably because i relaunched my container a couple of times this afternoon. ill make it a habit to deauthenticate/auth when relaunching my container for a new version. 

twitch was the culprit. did the usual remove/add.

**Comment by jprjr** [comment]
Having to remove/add the account is a failure, you shouldn't have to do that.

The fundamental error is for a long time, Twitch tokens never expired. Then one day, Twitch started enforcing token expiration on all new apps, so I've got two code paths now.

My production instance is grandfathered in. I thought I had recreated all my dev instances to use new tokens but I may not have. I'll go through and check.

**Comment by k1ck3r** [comment]
@jprjr i think you already solved the twitch issue, long versions ago?

**Comment by jprjr** [comment]
I'm pretty sure I had, but since my main production instance is grandfathered in to the expiration-free tokens, it's very possible that I missed something

**Comment by pogzie** [comment]
Possible to create a button to request a token re-issue? I wouldnt mind just clicking a button rather than removing-adding (since I have 3 streams pre-populated for every game a frequently play).

**Comment by jprjr** [comment]
That's totally possible - you just add your twitch account without removing it first.

**Comment by pogzie** [comment]
Interesting. I will take note of that.

**Comment by pogzie** [comment]
Token re-issue button now in the profile page, workaround to 're-add' without removing seems to be a reasonable workaround. Will close. thanks!

**Comment by jprjr** [comment]
Oh, that token re-issue on the profile page is just for the Multistreamer token, for loading up the chat widget in environments that can't save a cookie (like in OBS)
