### ISSUE TITLE
Auto push turned on, OBS is failing to connect

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#50]
Probably related to #49 , I tend to setup my multistreamer to automatically stream when it gets a feed from OBS, when im using this setting, OBS is complaining about my secret or my RTMP URL (which is, from my previous posts, already corrected). 

My hunch is that OBS is not smart enough to know that theres probably a different problem with multistreamer. Probably if a return code is returned to OBS to display another error (like stream cant start or something) would be more intuitive than blaming on the RTMP url or keys that is obviously correct.

**Comment by jprjr** [comment]
There's not really anything I can do about that right now. The nginx RTMP module is what sends the error, it doesn't have a method for specifying what the error message should be.

**Comment by pogzie** [comment]
Interesting. Oh well, I just made a personal note to re-authenticate everytime i re-launch the container.
