### ISSUE TITLE
ffmpeg persistent after stream stops

### ISSUE THREAD

**Issue by k1ck3r** [jprjr/multistreamer#51]
Hey JR,
unfortunately i'm facing the issue with persistent ffmpeg processes, even when the stream is stopped. using "Stop pushing" also can't terminate the processes running. tried both ways - with "require preview" switched on and off - again same results. tomorrow will try again 2 fresh installations but on both ubuntu/centos result is the same.

**Comment by jprjr** [comment]
How long do they persist, and what streaming software are you using? On my install, ffmpeg always quits immediately

On March 21, 2018 6:54:30 PM EDT, k1ck3r <notifications@github.com> wrote:
>Hey JR,
>unfortunately i'm facing the issue with persistent ffmpeg processes,
>even when the stream is stopped. using "Stop pushing" also can't
>terminate the processes running. tried both ways - with "require
>preview" switched on and off - again same results. tomorrow will try
>again 2 fresh installations but on both ubuntu/centos result is the
>same.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprjr/multistreamer/issues/51

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by k1ck3r** [comment]
at the moment, over 9 hours (https://gyazo.com/ad6cad859376efd57bae1e24bfc7a77c) using Xsplit

if you think this could be problem, will try OBS and report back. also something to note, i'm using compiled ffmpeg instead of one from repos. will try different version as well.

**Comment by k1ck3r** [comment]
it seems the issue is from ffmpeg, changing the version (recompiling) solve it. you can close that issue, but had to report that the twitch module is again broken at some point, because it needs to re-authenticate, and multistreamer drops the connection with error code 400 - no id specified.

**Comment by jprjr** [comment]
Testing a fix for Twitch now.

Basically, my token-refreshing code had a bug for the older, never-expiring tokens. So I fixed that bug, but broke the token-refreshing code. So I've reworked my fix for the older tokens.

Just waiting on my token to expire right now to see that it refreshes properly.

**Comment by k1ck3r** [comment]
thanks for noticing this. will wait for your confirmation before building the new version
