### ISSUE TITLE
Irc connect with ii

### ISSUE THREAD

**Issue by adardar211** [jprjr/multistreamer#52]
I'm a little confused on how to connect with a command line irc client. I'm trying to use ii so I can pipe chat from a costume rtmp service. Any advise would be appreciated.

**Comment by jprjr** [comment]
Hey hey! So with a custom RTMP stream, there's no chat (the RTMP protocol only transmits audio/video).

You'll want to use one of the modules (Facebook, Twitch, YouTube, Mixer) for getting chat meesages.

**Comment by adardar211** [comment]
I ended up using weechat. It supported sasl and has a fifo plugin to do what I need. I'm using another project to connect Instagram and multistreamer. It is grabing the comments from Instagram Live and sending to the IRC chat via weechat running as a service. It's not pretty but works.

**Comment by jprjr** [comment]
Oh nice! For future reference (not sure if ii supports SASL), you can also connect by sending your password with PASS
