### ISSUE TITLE
Account info persist into postgre even after user is deleted

### ISSUE THREAD

**Issue by k1ck3r** [jprjr/multistreamer#53]
hey imba,

stumbled the issue when i had to delete a user, cause of hijacked password, and after creating new user, she tried to add her account in twitch system returned already in use account. Adding same compromised username, the dashboard appeared with her twitch account. While writing this, i'm thinking that this might/should be a security feature but had to delete the stream-key at least from the db. also there are wrong EN translation button/links. will fix them when i find some spare time

best~

**Comment by jprjr** [comment]
Hey hey - I just wrote up a method to delete a user (and all their info) using the CLI.

You can run `multistreamer listusers` to get a list of users and their user IDs, then `multistreamer deluser (id number)` to delete a user.

I'll have it in my next release (11.6.0)

**Comment by k1ck3r** [comment]
thanks for implementing this!
