### ISSUE TITLE
Feature Request: Status Indicator

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#54]
So, it took me some time to re-setup my deployment (damn persistent storage) and once I got everything back up and running, I did a stream yesterday and it was fine but when I streamed today.. In my iPad I only check Facebook and Twitch. Visiting my YouTube page, I noticed that there was no stream. 

How hard would it be to have a status indicator in the dashboard on the main page (more on this below) to show that its pushing to YT/FB/Twitch or something. 

* I thought of putting it on the main page since the main page already show a little nice green button that the stream is pushing. Would be nice to have x number of green buttons if its already live on the services/accounts added to that stream.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
