### ISSUE TITLE
Facebooks New Permission Requests

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#55]
Due to the GDPR I think, Facebook is adjusting the permissions needed for the app. Is there any list of important permissions we would have to enable for our "multistreamer app" for this? 

```

App Review required by the listed review deadline(s) to retain Live Video API access
 
To retain API access to the following permissions and features you must submit your app for App Review by the listed review deadline(s).

Live Video API

Context: The permissions model developers use to publish video to user timelines, Groups and Pages is changing. Developers must submit their app for App Review before August 2, 2018. Learn More.

Action Required: For Multistreamer to maintain functionality, you will need to request the following permissions based on your needs as part of submitting your app for App Review:

To publish video to a user timeline, you will need to request the Live Video API feature, along with the new publish_video permission.

For Groups access you will need to request the publish_to_groups permission.

For Pages access, you will also need to request the publish_pages, manage_pages and pages_show_list permissions.

Note: The publish_to_groups permission is currently only available in development mode, it is scheduled to be enabled in production at a future date.

Next Steps: Start app review.
```

**Comment by jprjr** [comment]
I've released version 12.0.0, which should keep working with publishing video to user profiles and pages. Your users will likely have to re-add their Facebook accounts to grant the new permissions

**Comment by pogzie** [comment]
Cool thanks!

**Comment by asquelt** [comment]
facebook woes:
```Facebook



Szukaj

Konrad
Strona główna
Szukaj znajomych
Zaproszenia do grona znajomych
Wiadomości
Powiadomienia
Ustawienia konta
O FacebookuUtwórz reklamęUtwórz stronęTwórcy aplikacjiPracaPrywatnośćPliki cookieOpcje wyświetlania reklamRegulaminPomocUstawieniaDziennik aktywności
Facebook © 2018
PolskiEnglish (US)ślōnskŏ gŏdkaРусскийDeutschFrançais (France)ItalianoУкраїнськаEspañol (España)Português (Brasil)العربية
Zamknij
Błąd
Warning
Invalid Scopes: publish_video, user_events, manage_pages, publish_pages. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions
OK```

multistreamer 12.0.0 @ docker

**Comment by pogzie** [comment]
i think the facebook documentation on the wiki would need some review. once I get the time to do a silly workaround for that mandatory https for facebooks endpoints, i'd probably do a PR for improvements. 

but im considering just dropping facebook outright. all this jumping through hoops with multiple steps is getting tiresome. I have this in my internal shortcut documentation but surprise, looks like its not valid anymore: 

- Create at: https://developers.facebook.com
- Select Facebook Login (click Set Up) > Click Settings on the left
- Fill in the Valid OAuth redirect URIs with: http://<hostname>:8081/auth/facebook
- Get the API keys. They are the App ID and the App Secret on the Dashboard
- Make sure you publish a Privacy Policy document and upload it somewhere since you will need to set your app to Live for Multistreamer to be able to publish streams

**Comment by pogzie** [comment]
I've taken the time to comply with Facebook's SSL requirements only to end up also getting that warning from @asquelt .

**Comment by kylepauljohnson** [comment]
I have the same issue as well after setup.  Seems like a rather old issue.  Anyone make any progress?

**Comment by jessicah** [comment]
I've just been looking at the Facebook App Review, and in the list of permissions, "user_events" doesn't exist, so it's probably a matter of removing this particular scope...

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
