### ISSUE TITLE
Only listens to ipv6 interface

### ISSUE THREAD

**Issue by Llorx** [jprjr/multistreamer#56]
Having the default config, I have this:

![image](https://user-images.githubusercontent.com/702490/42724215-b1bcbe66-876e-11e8-89b5-0d08d9da98e3.png)

How to overcome this? Not listening to ipv4 interfaces.

**Comment by Llorx** [comment]
Yes, I've modified the `multistreamer/config.yml.tmpl` inside the `rootfs` (as I don't have access to the docker containers contents) and modified the `http_listen` to `http_listen: '8081 ipv6only=off'`, but nothing happens.

**Comment by k1ck3r** [comment]
file should be multistreamer/config.yml not multistreamer/config.yml.tmpl

also remove any other options like ipv6only=off if you want to be sure that every part of the config is properly filled

**Comment by Llorx** [comment]
The tmpl file is just a file that already exists with variables and such, so I thought that was processed at some point replacing the variables with config values.

Will try without tmpl.

**Comment by jprjr** [comment]
Question: have you tried connecting to an IPv4 address anyway? What happens if you do?

An IPv6 wildcard should be able to accept IPv4 connections as well.

What OS are you running on?

**Comment by Llorx** [comment]
Centos.

I would like to know if modifying the provided `tmpl` file I am doing something. I modified it to add the `ipv6only` thingy and also modified it to this:

`http_listen: '0.0.0.0:8081'`

Rebuilt the docker containers and still listening to the ipv6 interface.

**Comment by jprjr** [comment]
I'd need a few more details, like what version of CentOS. If you can provide what version of Docker you're using, that'd be great too.

Additionally, see my other question - have you tried connecting via IPv4 anyway, what kind of response do you get?

**Comment by Llorx** [comment]
Oh, I thought that you said if I forced it to listen to a IPv4 interface.

Yes, I started to debug because connecting via IPv4 throws me connection refused, so the first thing to do is to check for open ports.

I'm using CentOS 7 and Docker version 1.13.1.

**Comment by jprjr** [comment]
Modifying the config.yml.tmpl file should do what you want - how are you building the image and launching the container? Are you sure you're actually running the newly-built image?

**Comment by Llorx** [comment]
I'm new to docker so I'm not 100% sure, but searching around Internet I tried with this:
```
docker-compose rm // To remove
docker-compose up --build
```

**Comment by jprjr** [comment]
So the docker-compose file over in `jprjr/docker-multistreamer` doesn't specify a `build` parameter, just image. So using `docker-compose` to build won't actually build it.

The docker-compose file is in the old version 1 format, which doesn't let you specify an image tag and build instruction in the same service. If I update to version 2, users will have to update their override files to work with the new format.

so, to build the image, you'll want to run something like:

```
docker build -t jprjr/multistreamer:12.0.0-1 .
docker-compose up
```

Make sure that tag is what's in the `docker-compose.yml` file.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
