### ISSUE TITLE
https Redirect

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#57]
Facebook is now strictly implementing strict https for oauth redirect URIs. so things like `http://<hostname>:8081/auth/facebook` wouldnt work anymore. 

Possible to create an https redirect to the http endpoint rather than manually setting up SSL with this? 

Another option is to support adding of certs via the environment variables.

**Comment by jprjr** [comment]
Well, an HTTPS redirect to HTTP would require HTTPS to be setup to even accept the incoming connection, meaning you may as well be using HTTPS.

The thing about SSL is it's very, very site-specific. There's a lot of deployment options, you can automate with Let's Encrypt, you can buy certs, you can enforce specific ciphers, add specific headers for HSTS, etc etc. There's a lot.

For example, my setup is stunnel in front of multiple services, including Multistreamer. stunnel decrypts the incoming connection and routes to a different service based on the SNI hostname (so I can do things like run irc, ssh, and https all on port 443).

It's a specific choice to not setup HTTPS on the sysadmin's behalf. I recommend setting up nginx or haproxy as an SSL terminator in front of Multistreamer.

**Comment by pogzie** [comment]
Well, i've thought of that to to just have an https redirect via nginx but if its something you think should be the prerogative of the user, i'd just spend the time. 

Though it would really be nice to have this as a feature in the future. While I use the dockerized version, it would really be convenient to not have to setup another thing just to get through this FB hoop.

**Comment by pogzie** [comment]
@jprjr would it be doable if we convert this feature request to have https support for the web service multistreamer is using? additional ENV variables for certs? 

Im planning to just get a root cert from LetsEncrypt and just load it on here.

**Comment by jprjr** [comment]
I guess I'm having a bit of a disconnect - I *always* setup an HTTP and HTTPS reverse proxy, whether I'm running a basic blog, something like Multistreamer, and so on (or in my case, a whole lot of services). I don't want users to have to type in a specific port, so I bind Multistreamer (and other webapps) to localhost and setup nginx in front, to route requests to the right backend based on hostname.

To me, there's just not a lot of value in adding HTTPS support directly into Multistreamer, since people should be setting up HTTPS anyway. I really think that should be up to the user deploying the software to figure out the right HTTPS setup for their use-case.

**Comment by pogzie** [comment]
I agree, _but_ now that FB is requiring this hoop for us to jump in and I assume most of the users of multistreamer are the ones like me who wants to multistream to twitch/yt/fb without paying for restream.io.. i personally would just skip the complexity and just suck it up and give up fb streaming and go with restream. 

I hope I havent offended, appreciate the great work you've done and i've streamed more than 100 hours with multistreamer and its just sad we're just all victims of facebooks policy change. 

Perhaps as something easier, is it possible to support https if lets say the config has some ENV variables for the certs path? 

I just plan to generate via letsencrypt a wildcard and just use it with multistreamer.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
