### ISSUE TITLE
Version or Build Number

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#58]
Hi, I typically just relaunch my container with the option to force pull a new image. But just for sanity, is it possible to add the current version number of Multistreamer lets say, on the login page? This would make it easier for me to identify that I indeed got the new version.

**Comment by jprjr** [comment]
Done and done, just pushed up version 12.1.0 - it will show version information on the main page (after logging in).

I also added an option to the config.yaml file to hide the version number, if desired, and added an entry to the config.yaml.example file

**Comment by pogzie** [comment]
Question, I pulled the new docker image, where can I find it? Login page is the same, Dashboard it the same, profile is the same..

**Comment by jprjr** [comment]
Add `MULTISTREAMER_SHOW_VERSION: 'true'` to your `docker-compose.override.yml` file, and it should show up.

**Comment by pogzie** [comment]
Confirmed, saw version number at the bottom. Closing.
