### ISSUE TITLE
ffmpeg not running after overriding FFMPEG Arguments

### ISSUE THREAD

**Issue by screamingDanana** [jprjr/multistreamer#59]
Hello,

I am multistreaming to Twitch and Facebook. I wanted to transcode my stream to Facebook and input all the necessary arguments into the FFMPEG Args field. Everything seems okay after I clicked submit and Go Live, no errors so far. When I checked my stream on my Twitch channel, it states that I'm offline. Checked my Facebook post and it showed it is unavailable or not found. I accessed the terminal to look for running processes using 'top' and ffmpeg is not running. I even tested with default args '-acodec copy -vcodec copy', still the result is consistent.

The stream works/ffmpeg is running when the FFMPEG Args is blank but doesn't after I override the FFMPEG Args. Also, I can't save blank FFMPEG Args after I clicked submit. It just re-input the previous arguments. If I put a space into the field, it saves but ffmpeg is not running as well.

Any ideas? Thanks in advance.

**Comment by DanialFrost** [comment]
Thanks for fixing the blanking problem. The stream works by default without adding the arguments. It doesn't work after I added into the field. Not sure whether it is on my end or yours.

**Comment by DanialFrost** [comment]
Update: Looks like blanking the ffmpeg args field works but replacing the arguments doesn't.

Example:
Input any arguments into the field e.g 
> -c:v copy -c:a aac -b:a 96k

Delete some of the arguments so that it becomes
> -c:v copy -c:a copy

After clicked submit, it changes back to
> -c:v copy -c:a aac -b:a 96k

**Comment by DanialFrost** [comment]
Sorry, I closed by accident

Update: Looks like blanking the ffmpeg args works. The args field is saved but if I were to replace/tweak it, it changes back to the previous args.

Example:
1. Add any FFMPEG Args such as
> -c:v copy -c:a aac -b:a 96k

2. Remove/replace some parameters
> -c:v copy -c:a copy

3. After clicking submit, the field changes back to
> -c:v copy -c:a aac -b:a 96k

Also, ffmpeg still doesn't run after I blanked the field. I have to restart multistreamer.service for it to work again. Even after adding arguments into the field and restart the service, ffmpeg still doesn't run. This is a strange bug.

**Comment by ralee87** [comment]
i have the same problem.Any solution for this?

**Comment by lhorace** [comment]
I have ran into the same problem here, the workaround is to empty the field, hit submit. This will throw an error, hit refresh (or navigate to the same page), now enter your new parameters.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
