### ISSUE TITLE
Returning path from networks

### ISSUE THREAD

**Issue by k1ck3r** [jprjr/multistreamer#60]
hello.

in the last 3-4 weeks i'm receiving complains from my friends, that they are getting error once the complete the steps of authorizing mutlistreamer from Youtube. i was able to reproduce the error, but sometimes, the authorization just completes fine. 

https://gyazo.com/015f47fde63709e25667aab481b8d1fb

This is the exact error returned from multistreamer, and below is the debug messages from multistreamer (will cut most of the information because of keys and privacy)

https://gyazo.com/fa115d7eaf574a9e135c8186c6827ab7

if any of you guys, have an insight on this, please let me know.

**Comment by k1ck3r** [comment]
https://gyazo.com/688c6852a1615807c8ba5864cd4c02c6

ok, it's related with ipv6. getting this message once i disable system-wide the ipv6. any idea how to solve this?

**Comment by jprjr** [comment]
I do! So by default, Multistreamer has no idea what kind of network connections it actually has. When it resolves DNS entries, it gets back ipv4 and ipv6 entries.

You just have to add "ipv6=off" to your "dns_resolver" config entry.

So for example, if you had:

```
dns_resolver: '8.8.8.8'
```

Change it to

```
dns_resolver: '8.8.8.8 ipv6=off'
```

And you'll no longer query for ipv6 addresses.
