### ISSUE TITLE
Facebooks New Restrictions

### ISSUE THREAD

**Issue by pogzie** [jprjr/multistreamer#62]
With the Facebook Login module castrated, is there any other way we can work around this?

Currently, Facebook is now restricting Pages API to verified as stated in https://developers.facebook.com/docs/pages/ 

While we can still stream to our personal Facebook profiles, I think this defeats the purpose of us small time streamers to effectively use this to stream to our pages.

**Comment by jprjr** [comment]
I've been keeping an eye on this, as far as I can tell the restrictions haven't kicked in yet.

I've never actually submitted my app for app review, it's been set to "live" for some time and still works for pushing to my page every week, the page isn't verified, the app doesn't have business verification, etc. All my users are manually added as testers of the app, there's only a handful of us using my Multistreamer instance.

Have you run into any problems pushing video to your page?

**Comment by Arcanum417** [comment]
I created the app now and cannot seemt o choose page anywhere. Seems I can grant permissions to manage my pages, but looks like I should be able to choose a page to stream to in multistreamer but it just defaults to my personal profile.
