### ISSUE TITLE
Mixer FTL support?

### ISSUE THREAD

**Issue by Toucan-Sam** [jprjr/multistreamer#63]
Hey guys,
This looks brilliant and I'll be setting it up over the weekend. Thank you for all your hard work!

I've been using an NGINX based multistream setup to push to Twitch and Mixer, but disappointed that I can't quite work out pushing to Mixer via their FTL protocol. It looks like a WebRTC stream but with a few extra quirks.

Has anyone else worked this out yet? :)
- Toucan

**Comment by eaba** [comment]
Hi,
I have interest in the SRT protocol, in the works yet?
I also sent you an email (john at jrjrtech dot com)

**Comment by jprjr** [comment]
As far as I know, nobody's written a module for ingesting SRT streams into nginx. I thought about making a lua wrapper for libsrt, but I *think* it requires using it's own wrappers for UDP sockets (though admittedly, I haven't had a lot of time to check on it).

Re: emails, I never respond to direct emails about multistreamer. Anything you'd send as an email should be posted as an issue.

**Comment by eaba** [comment]
Does this support concurrent users streaming at the same time - say youtube type of service? What will be the best sys specs to supports thousands of concurrent streams?

**Comment by Toucan-Sam** [comment]
@eaba Multistreamer is a tool to allow people to push a single stream to multiple destinations. IE, stream your video game to Facebook, Twitch, and YouTube all at the same time. It is not a replacement for any of those services. Viewers would watch your stream the stream through (Facebook, Twitch, YouTube, etc) and (Facebook, Twitch, YouTube, etc) would handle the video delivery.

It sounds like you might want to check out the [OBS hardware requirements](https://obsproject.com/wiki/System-Requirements).

@jprjr Thanks for the responses. NGINX is still NGINX and probably the barrier at this stage without running multiple copies of OBS simultaneously with different endpoints. Surprised OBS doesn't just support a 'add an endpoint' option. Probably related to how it encodes video though. What codec, resolution, bitrate, etc etc.
Still appreciate this being published though. :)

**Comment by eaba** [comment]
@Toucan-Sam thanks.
What I was trying to say is having something like a SAAS where multiple users can multi-stream to facebook, youtube etc at the same time.

**Comment by Toucan-Sam** [comment]
Hi @eaba ,
This is not designed as a SAAS solution, at least at this stage. There is no web/management interface. If you wanted to make a feature request, probably best to do that in a separate issue as it's not related to FTL support. :)

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
