### ISSUE TITLE
Stopping puller doesn't reap ffmpeg process

### ISSUE THREAD

**Issue by lhorace** [jprjr/multistreamer#66]
Hello there,

I'm re-opening an old issue, see #16, this was suppose to be fixed in 9.0.0 a while back. While I mimic the behavior with my PR #65. It seems to be a bit inconsistent?

**EDIT:** ~~Seems to behave as expected, I've only come across one instance where it failed to reap ffmpeg process.~~ Scratch that, it's inconsistent.

```
Feb 22 16:20:05 ubuntu1804-mutistreamer multistreamer[26843]: 2019/02/22 16:20:05 [debug] 26872#26872: *5881 [lua] redis.lua:27: publish(): Redis:publish: [process:start:pull] {"worker":26872,"id":3}
Feb 22 16:20:05 ubuntu1804-mutistreamer multistreamer[26843]: 2019/02/22 16:20:05 [debug] 26872#26872: *5 [lua] process_manager.lua:50: [Process Manager] Starting: /usr/bin/ffmpeg -v error -re -i rtmp://127.0.0.1:1935/multistreamer/15379b41-98ab-4503-9bbe-79dc6db3886e -c:v copy -c:a copy -f flv rtmp://127.0.0.1:1935/multistreamer/ea2c493f-963e-4b5e-9499-5e08db75bbd2
Feb 22 16:46:49 ubuntu1804-mutistreamer multistreamer[27623]: 2019/02/22 16:46:49 [debug] 27653#27653: *1878 [lua] redis.lua:27: publish(): Redis:publish: [process:end:pull] {"id":3}
Feb 22 16:46:49 ubuntu1804-mutistreamer multistreamer[27623]: 2019/02/22 16:46:49 [debug] 27653#27653: *5 [lua] process_manager.lua:327: func(): [Process Manager] Stopping puller with id 3
```

~~I'm seeing the same behavior for FFMpeg pushers as well, they are not getting reap.~~

Seems to quit after time lapse.

`lua-resty-exec 3.0.3-0`
Regards

**Comment by jprjr** [comment]
Thanks for the report - I'll take a look this weekend

**Comment by lhorace** [comment]
Sweet!

**Comment by lhorace** [comment]
I dig into this for a bit, seems this is the commit that changed the previous behavior https://github.com/jprjr/multistreamer/commit/a61bf63552fac28f165c8da5588ead4fd8abe353. I'm implement the old behavior and report back my findings.

**Comment by bojanlisa** [comment]
Any progress with the ffmpeg process?
Im having the same problem, ffmpeg stops only when the incoming rtmp stream stops.
It ignores the push/pull buttons.

**Comment by lhorace** [comment]
Hey @bojanlisa,

When jprjr updated the installer, I noticed I was using an older version of sockexec, though I haven't inspected the current behaviour to determine if it's working as expected, does updating sockexec to the current release fix it for you?

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
