### ISSUE TITLE
Feature Request : Include Periscope ?

### ISSUE THREAD

**Issue by rubensben** [jprjr/multistreamer#70]
Maybe including the streaming platform of twitter would be a good idea ? From what I understand, they also have an API system that works with RTMP : https://help.pscp.tv/customer/en/portal/articles/2600293-what-is-periscope-producer

Kindly !

**Comment by lhorace** [comment]
That would really be a cool idea, though, AFAIK, you can't interact with the Chat API. Eg. you could read, but I'm not sure you can send, moderate, or edit.

What kinds of things you would like to see happen?

**Comment by rubensben** [comment]
Hi @lhorace , well, push the video with a title and description would already be a great step :)

**Comment by jprjr** [comment]
I'll try taking a look at this. I recall in the past (I think 2016), 
you had to sign up as a Partner and access was really, really limited. 
I'll see if they've opened Periscope Producer up a bit.

**Comment by lhorace** [comment]
I can help with testing and fixes! If it's possible!

**Comment by rubensben** [comment]
same here

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
