### ISSUE TITLE
FFMPEG Pull

### ISSUE THREAD

**Issue by umekzg** [jprjr/multistreamer#71]
FFMPEG Pull Args dont add  -c:v copy -c:a copy
You need to do it manual or it will use default ffmpeg encoding profile and waste a lot of processor usage.

**Comment by lhorace** [comment]
Hey @bojanlisa,

AFAIK, it shouldn't? Are you requesting an enhancement ? Not sure how this should be implemented, search for the string `-c:v` is missing and append `-c:v copy`? The point of FFMPEG Pull Args, while not feature complete; offers flexibility. I suspect, adding a text box RTMP url with a custom checkbox just for those who want custom options might work here.

Cheers

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
