### ISSUE TITLE
IRC connection reset

### ISSUE THREAD

**Issue by lhorace** [jprjr/multistreamer#74]
Hey again,

IRC doesn't seem to work for me on my end and I'm a bit confused about the setup. I just need to sit down and spend a few hours figuring why things aren't working for me. At any rate, what is haproxy for? It appears to me it's a frontend to IRC, though when I attempt to connect to it directly with Irssi on port 6697, which is the registered service port for IRCS, it throws an error `BAD REQUEST`. My suspicion, it's expecting HTTP protocol? The link provided by the WebUI ircs://hostname/channel,needpass, the connection just resets? It doesn't even negotiate TLS?

Cheers

**Comment by k1ck3r** [comment]
HAProxy is used for SSL termination - client connects through SSL socket, and HA proxying the request inside to plain text. Your confusion comes from the client you are using, almost sure. The following connect string can be used with BitchX and mIRC clients to connect to SSL terminated IRC service

```
/server +irc.multistreamer.server:6697
```

**Comment by jprjr** [comment]
Yeah, I'd make sure your client is using SSL. Web browser support for irc links is really hit or miss, if you're clicking the link it might not be opening correctly.

**Comment by lhorace** [comment]
Thanks @k1ck3r 

```
/server +irc.multistreamer.server:6697
```

I have Multistreamer running on a AWS instance and I just realize when I was setting it up with Hexchat. I was using the wrong port. I'll test again and report back.

**Comment by lhorace** [comment]
Huh, something is broken here:

```
Connecting to rtmp.lhprojects.net (52.14.110.118:6697)
* * Subject: /O=Digital Signature Trust Co./CN=DST Root CA X3
* * Issuer: /O=Digital Signature Trust Co./CN=DST Root CA X3
* * Subject: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
* * Issuer: /O=Digital Signature Trust Co./CN=DST Root CA X3
* * Subject: /CN=rtmp.lhprojects.net
* * Issuer: /C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
* * Certification info:
*   Subject:
*     CN=rtmp.lhprojects.net
*   Issuer:
*     C=US
*     O=Let's Encrypt
*     CN=Let's Encrypt Authority X3
*   Public key algorithm: rsaEncryption (4096 bits)
*   Sign algorithm sha256WithRSAEncryption
*   Valid since Feb 25 23:40:56 2019 GM to May 26 23:40:56 2019 GM
* * Cipher info:
*   Version: TLSv1/SSLv3, cipher ECDHE-RSA-AES256-GCM-SHA384 (256 bits)
* Connected. Now logging in.
* HTTP/1.0 400 Bad request
* Cache-Control: no-cache
* Connection: close
* Content-Type: text/html
* 
* <html><body><h1>400 Bad request</h1>
* Your browser sent an invalid request.
* </body></html>
```

**Comment by lhorace** [comment]
Fixed, I'll post a PR later on today!

**Comment by jprjr** [comment]
Awesome!! Thank you

On March 27, 2019 11:37:21 AM EDT, Horace <notifications@github.com> wrote:
>Fixed, I'll post a PR later on today!
>
>-- 
>You are receiving this because you commented.
>Reply to this email directly or view it on GitHub:
>https://github.com/jprjr/multistreamer/issues/74#issuecomment-477213978

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by k1ck3r** [comment]
@lhorace sorry i mislead you a bit with the command you should use to connect to multistreamers "irc" server.
The important thing that should be mentioned, is that your nickname within the IRC client have to match your multistreamer username. the following command (i just tested on my instance) will guarantee you proper connect using mIRC (win client) /will try to find the instance where i compiled BitchX to provide additional info/

```
/server irc.multistreamer.hostname +6697 pass
```
where pass should be your password for user defined into the following. check the gif below

[![Screenshot from Gyazo](https://gyazo.com/77feb9993313ecdf0ccd8514d5711a21/raw)](https://gyazo.com/77feb9993313ecdf0ccd8514d5711a21)

**Comment by lhorace** [comment]
@k1ck3r Thanks, got it working!

@jprjr https://github.com/jprjr/multistreamer-installer/pull/13
