### ISSUE TITLE
[feature request] Can the chat widget be transparent?

### ISSUE THREAD

**Issue by lhorace** [jprjr/multistreamer#75]
Hey,

I was testing the chat widget in a stream yesterday and I noticed it isn't transparent, seems to me the chat widget would need to take up a portion of the screen? Probably could be done hacking css?

**Comment by gdhgdhgdh** [comment]
15 months later, but I bumped into this yesterday, and my use case was with OBS. When using the 'Browser Plugin' you can provide a custom CSS. Please feel free to use the attached.

[chat-css.txt](https://github.com/jprjr/multistreamer/files/4761774/chat-css.txt)

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
