### ISSUE TITLE
[REQ] webhooks

### ISSUE THREAD

**Issue by k1ck3r** [jprjr/multistreamer#76]
hey jr,

i wonder will it be hard for you , to implement function for deleting webhooks, based on their stream id, and their actual id? not sure, but this might be intended. personally want to clear the db, of hooks attached to dead places/forgotten channels. just because i'm now over 1k users (not all active, but registered) and i don't want to delete users anymore, just because of their dead hooks.

ty in advance

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
