### ISSUE TITLE
Make project fail - 2 errors

### ISSUE THREAD

**Issue by Ennorath** [jprjr/multistreamer#78]
![image](https://user-images.githubusercontent.com/22742638/56365899-7f900380-6224-11e9-8d1b-650ee302592f.png)

**Comment by Ennorath** [comment]
Ubuntu 18.04,

**Comment by k1ck3r** [comment]
i think this is related to nginx compilation within the openresty setup. strongly suggest you to use https://github.com/jprjr/setup-openresty to setup your openresty instance.

**Comment by Ennorath** [comment]
> i think this is related to nginx compilation within the openresty setup. strongly suggest you to use https://github.com/jprjr/setup-openresty to setup your openresty instance.

do you know how to link multistreamer + postgres-auth-server, problem is that both of them migrate "user" table in database. is will be ok, if i will edit migration and add all columns in both?

**Comment by k1ck3r** [comment]
checkout https://github.com/jprjr/multistreamer-installer - it should help you further ;)
