### ISSUE TITLE
Twitch API

### ISSUE THREAD

**Issue by Pimmal** [jprjr/multistreamer#79]
This is the error i get when conecting to twitch with your docker image

> {"status":400,"message":"Sorry, the scope you are requesting is currently unavailable. Please request new scopes documented at https://dev.twitch.tv/docs/authentication/#chat-and-pubsub."}

**Comment by k1ck3r** [comment]
hey,

in this message twitch's api tells you (most probably) that there is an issue with the dev application config which you should be made. so, did you create the application in their development portal (https://dev.twitch.tv/)? if yes, did you checked (precisely) that the call-back URL which you entered is reachable from the internet? 

another thing, is that in early March, there was a change in twitch's chat api/syntax and i'm not completely sure that the docker image is updated. you can check about what should be changed within the Multistreamer itself check this [merge](https://github.com/jprjr/multistreamer/commit/e238c043bfd840a6e7b1a324d6c85209c61ab4ee) and follow this [pull request](https://github.com/jprjr/multistreamer/pull/69) regarding twitch's chat changes

**Comment by Pimmal** [comment]
I have now tried it with the installer and also have a lot of problems. Have opened a issue there https://github.com/jprjr/multistreamer-installer/issues/15

**Comment by Arcanum417** [comment]
Same thing, setup from the docker image. The image seems to be built from the last master commit https://hub.docker.com/r/jprjr/multistreamer/builds .

**Comment by jprjr** [comment]
Done, pushed new multistreamer docker builds
