### ISSUE TITLE
Possible to set IRC client to OPER?

### ISSUE THREAD

**Issue by republicus** [jprjr/multistreamer#80]
I am trying to give permitted IRC users OPER role so that I can set configure a custom discord bot that will relay IRC commands through discord-irc (https://github.com/reactiflux/discord-irc)

discord-irc connects and does most of what I need.
However, my livestreams are frequented by trolls and I wish to be able to send a KICK, KICKBAN, QUIET etc command from discord to mute the webhooks into discord (which would allow those users to remain in communication on the network chat directly -- just not flooding discord)

However, whenever I send a command my permitted IRC users are unable to pass any args to the IRC server because they are not an Operator.

The only operator I see is named **root** and I cannot figure out to connect as root to grant OPER status to select clients. I don't see in the irc/server.lua or elsewhere that would lead me to root's credentials/password or any definition that would allow to adjust who would be granted operator on IRC startup.

I may try to create a new bot command but I am just learning Lua since using this project.

What is the best way to grant OPER status to clients?

**Comment by jprjr** [comment]
So the built-in IRC server is operating with the bare minimum needed to work with IRC clients. There's no real "operator" concept, the code to respond to topic changes, kicks, etc is mostly there to meet the minimum specs to meet the IRC RFC. I'm actually pretty amazed that discord-irc works!

I would recommend banning trolls on Twitch/YouTube/etc.
