### ISSUE TITLE
Option to not end youtube stream on lost signal (same as FB)

### ISSUE THREAD

**Issue by Arcanum417** [jprjr/multistreamer#81]
Facebook already has an option to not "End live video when stream ends *".
Youtube has the same workflow with events, it would be great to add the same option for yt.
Or just do not run post streamend routine on pushing disconnect and require end stream button beeing pressed. (in case the "Require Preview before going live" is enabled)
The use case is to have an option to recover form connection loss or some other disconnect on the pushing side.
![chrome_OvOFue66Py](https://user-images.githubusercontent.com/6292869/70358342-6dc5a400-1879-11ea-94c5-5ac69adc5da2.png)

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
