### ISSUE TITLE
Plans for Instagram streaming?

### ISSUE THREAD

**Issue by joneschrisan** [jprjr/multistreamer#83]
Hi are there any plans to add live streaming for Instagram?

**Comment by jprjr** [comment]
Instagram does not have an API for third-party apps to stream, at 
least as far as I'm aware - so no.

**Comment by joneschrisan** [comment]
rtmp://live-upload.instagram.com:80/rtmp/

and https://github.com/Instagram/python-instagram

Might be able to do something with that

**Comment by jprjr** [comment]
That Python module only covers the official instagram API, which is very limited, and being retired this year.

I have a hard enough time keeping up-to-date with the official, documented APIs. I'm not interested in having to keep up with undocumented, unsupported APIs.
