### ISSUE TITLE
Facebook Scheduled Streams not in list

### ISSUE THREAD

**Issue by rivo** [jprjr/multistreamer#84]
I'm not sure if Facebook changed something but a live stream I scheduled through a Facebook page didn't show up in Multistreamer's drop-down list. Yes, I selected the corresponding Facebook page and hit "Submit", even refreshed a few times. But the only option was to create a new event/stream. (It worked with YouTube.)

I'm not sure if I'm doing something wrong or if Facebook changed their API but it would be nice to have this option (again).

I'm using the Multistreamer Docker repo. Installed it a few days ago so it's the current version.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
