### ISSUE TITLE
Terms of Service page

### ISSUE THREAD

**Issue by Soundguy8** [jprjr/multistreamer#85]
YouTube is being very difficult to work with.  On my developer API, I am allowed 10,000 queries per day.  This amounts to about 30 minutes of streaming.  I requesting an increase and after jumping though several hoops, they are telling me that I have to put a Terms of Service page and include a link to YouTube terms of service.  Can we have a way to do some basic customization on the login landing page?  Either that or add a custom link at the bottom of the page?

Thank you for the awesome work you have done on this!!!

**Comment by jprjr** [comment]
Fixed with version 12.3.0 - you can add any number of links to the bottom of the page.
