### ISSUE TITLE
Referenced maintained version of RTMP module

### ISSUE THREAD

**Issue by jessicah** [jprjr/multistreamer#87]
The most maintained version of the RTMP module is now https://github.com/sergey-dryabzhinsky/nginx-rtmp-module

**Comment by silksow** [comment]
That fork may be the "most maintained", but the latest release is almost two years older than Arut's.

https://github.com/sergey-dryabzhinsky/nginx-rtmp-module/releases/tag/v1.1.7.10

https://github.com/arut/nginx-rtmp-module/releases/tag/v1.2.1

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
