### ISSUE TITLE
YouTube doesn't appear to stop livestreaming when RTMP stream ends

### ISSUE THREAD

**Issue by jessicah** [jprjr/multistreamer#88]
Using OBS, I have a scene that automatically ends the stream. However, YouTube appears to think that the stream is still live, at times for more than an hour. Mixer appears to end the stream properly, so it seems isolated to YouTube.

**Comment by amasu** [comment]
Same issue here

**Comment by Richiachu** [comment]
Same bug, stream was Live for an addition 4 hours.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
