### ISSUE TITLE
Writing comments on FB page / profile

### ISSUE THREAD

**Issue by gdhgdhgdh** [jprjr/multistreamer#89]
On https://github.com/jprjr/multistreamer/wiki it's clearly noted that multistreamer does not support writing comments. 

Is this from a lack of FB API, or some violation of terms of service for one account acting as a 'bot proxy' ?

**Comment by gdhgdhgdh** [comment]
Just following up on this as I've now spent some time with the FB dev docs and Graph API Explorer. The short version is you can only reply to existing comments on a video. FB will not permit you to post a new comment of your own.

`GET /v7.0/<video-id>/comments` will retrieve a list of comment ID's. If you POST to /v7.0/<comment-id>/comments as a Page then it works fine:

![image](https://user-images.githubusercontent.com/5349029/84131697-cfd7af80-aa3c-11ea-989f-24c0f8ee2927.png)

![image](https://user-images.githubusercontent.com/5349029/84131718-d534fa00-aa3c-11ea-8fe6-785e6729e972.png)

How do you feel about implementing this awkward restriction in the IRC? At the moment, the FB bot just says 'not supported', when it could work provided it can find a recent matching comment from that user. It would only need to keep a history of, say, 50 most recent user IDs + comment IDs.

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
