### ISSUE TITLE
Facebook Module does without SSL

### ISSUE THREAD

**Issue by aereaco** [jprjr/multistreamer#91]
Hello, I got things all setup up. I'm using NGINX and managed to incorporate Let's Encrypt using Certbot. I'm able to reach the the app via ssl port 443. Youtube is work pretty well. Facebook however is giving me all sort of issues though. Has there been change other than requiring an SSL. Have others reported the issue?

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
