### ISSUE TITLE
Using FFMPEG Args

### ISSUE THREAD

**Issue by eskapiste** [jprjr/multistreamer#93]
Hi there guys!
I am trying to setup a restream to various platforms, including Instagram. The problem with instagram is that, originally?, i have 16:9 video (1920*1080) and by default it appears in instagram without rotation and that means that i can only see a small portion of original frame. I tried to rotate my video by 90 degrees in OBS and it does the trick, but the thing is that i need my video to be restreamed without rotation to platfroms such as Facebook, Youtube etc and with 90 degrees rotation to Instagram. I tried to use FFMPEG args but it didnt work, it does not send anything to any platfrom if i write some specific arguments.
I tried these combinations

ffmpeg -c:v copy -metadata:s:v rotate="90" -c:a  
 ffmpeg -i input -vf transpose=2 output
ffmpeg -c:v copy -vf transpose=2 -c:a

i dont have enough knowledge about using arguments so i want to ask for your advice how to use it properly to rotate my video for only one destination.

Thanks!

**Comment by jprjr** [comment]
Did you have `ffmpeg` in the arguments? Try removing that

**Comment by eskapiste** [comment]
nope, i didnt use ffmpeg at the beginning.
the only arguments that work are "-c:v copy -c:a copy" but those are default ones. how should i insert a rotation argument in here?

**Comment by eskapiste** [comment]
i tried these options - none of them work:

-c:v copy -metadata:s:v rotate="90" -c:a copy
-c:v copy-vf transpose=2 -c:a copy

**Comment by jprjr** [comment]
Unfortunately, I'm not familiar with how to stream video to instagram, what they're expecting, etc. 

I do know if you're doing a video filter (`-vf transpose=2`), you can't use the `copy` codec, you'll have to re-encode.

I would suggest making a pre-recorded video locally, and figure out how to stream to instagram with ffmpeg locally first, like:

```bash
ffmpeg -re -i some-premade-video.mp4 -c:v copy -c:a copy -f flv rtmp://whatever/the/url/for/instagram/is
```

That `-c:v copy -c:a copy` section is the part of the CLI you'll want to edit and paste into your ffmpeg arguments.

**Comment by eskapiste** [comment]
lets put IG aside.
i tried these strings for youtube too,

> -c:v copy -metadata:s:v rotate="90" -c:a copy
> -c:v copy-vf transpose=2 -c:a copy

 it didnt wor.l.

i ll try your option for sure.
and what should i put instead of "some-premade-video.mp4" if i am restreaming live video?

**Comment by jprjr** [comment]
I've been considering discontinuing this project for some time now. I'm sorry I couldn't solve your issue, but I just don't enjoy working on multistreamer anymore.
